language: clojure
lein: lein2
script: lein2 test
jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y pdftk
  - sudo apt-get install -y file
  - sudo apt-get install -y zip
  - sudo apt-get install -y graphicsmagick